# Generated by Django 5.1 on 2024-09-03 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_payee', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=255)),
                ('quantite_minimum', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrixProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_produit', models.FloatField()),
                ('date_prix_produit', models.DateField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='borditasyapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_produit', models.FloatField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='borditasyapp.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='borditasyapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_depense', models.CharField(max_length=255)),
                ('quantite_stock', models.FloatField()),
                ('prix_achat_dep', models.FloatField()),
                ('prix_vente', models.FloatField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='borditasyapp.produit')),
            ],
        ),
    ]
