# Generated by Django 5.0.7 on 2024-07-15 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('est_payee', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nom_produit', models.CharField(max_length=255)),
                ('date_produit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PrixProduit',
            fields=[
                ('id_prix_produit', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('prix_produit', models.FloatField()),
                ('date_prix_produit', models.DateField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borditasyapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('qte_produit', models.FloatField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borditasyapp.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borditasyapp.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('designation_depense', models.CharField(max_length=255)),
                ('quantite_stock', models.FloatField()),
                ('prix_achat_dep', models.FloatField()),
                ('prix_vente', models.FloatField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borditasyapp.produit')),
            ],
        ),
    ]
