# Generated by Django 5.1 on 2024-10-02 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borditasyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='prix_vente',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='borditasyapp.produit'),
        ),
    ]
