# Generated by Django 5.1 on 2024-10-04 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borditasyapp', '0002_alter_stock_prix_vente_alter_stock_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_facture',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
