# Generated by Django 5.1 on 2024-10-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borditasyapp', '0003_facture_date_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_stock',
            field=models.DateField(auto_now=True),
        ),
    ]
