# Generated by Django 5.1 on 2024-10-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borditasyapp', '0004_stock_date_stock'),
    ]

    
    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW ProductWithActualPrice AS
            SELECT p.id, p.nom_produit, s.prix_vente
            FROM borditasyapp_Produit p
            JOIN (
                SELECT produit_id, prix_vente, MAX(date_stock) AS latest_date
                FROM borditasyapp_Stock
                GROUP BY produit_id, prix_vente
            ) s
            ON p.id = s.produit_id order by p.nom_produit;
            """,
            reverse_sql="DROP VIEW IF EXISTS ProductWithActualPrice;"
        ),
    ]
