# Generated by Django 5.1 on 2024-10-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borditasyapp', '0004_stock_date_stock'),
    ]

    
    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW ProductWithActualPrice AS
            SELECT p.id, p.nom_produit, s.prix_vente, s.prix_achat_dep
            FROM borditasyapp_Produit p
            JOIN (
                SELECT produit_id, prix_vente, prix_achat_dep
                FROM borditasyapp_Stock s1
                WHERE date_stock = (
                    SELECT MAX(date_stock)
                    FROM borditasyapp_Stock s2
                    WHERE s1.produit_id = s2.produit_id
                )
            ) s
            ON p.id = s.produit_id ORDER BY p.nom_produit;
            """,
            reverse_sql="DROP VIEW IF EXISTS ProductWithActualPrice;"
        ),
    ]
