# Generated by Django 5.1 on 2024-10-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borditasyapp', '0005_create_product_with_actual_price_view2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='designation_depense',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantite_stock',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
