# Generated by Django 5.1 on 2024-10-08 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borditasyapp', '0006_alter_stock_designation_depense_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE VIEW list_stock AS
            SELECT * FROM 
                borditasyapp_stock s
            WHERE prix_vente is not null;
            """,
            reverse_sql="DROP VIEW IF EXISTS list_stock;"
        ),
        migrations.RunSQL(
            """
            CREATE VIEW list_depense AS
            SELECT * FROM 
                borditasyapp_stock s
            WHERE prix_vente is null;
            """,
            reverse_sql="DROP VIEW IF EXISTS list_depense;"
        ),
    ]
