# Generated by Django 5.1 on 2024-10-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borditasyapp', '0006_alter_stock_designation_depense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(max_length=255)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('role_user', models.CharField(max_length=255)),
            ],
        ),
    ]
