# Generated by Django 5.1 on 2024-10-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borditasyapp', '0007_user_delete_prixproduit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
