# Generated by Django 5.1 on 2024-10-09 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borditasyapp', '0008_create_list_product_with_remaining_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_stock',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
