# Generated by Django 5.1 on 2024-10-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borditasyapp', '0009_user'),
        ('borditasyapp', '0010_create_view_commandePrice'),
    ]

    operations = [
    ]
